import { APP_NAME } from "@/utils/constant";

export default {
  confirm: "Confirm",
  cancel: "Cancel",
  radio: "Radio",
  multiple: "Multiple",
  light: "Light",
  dark: "Dark",
  systemTheme: "Auto",
  language: "Language",
  port: "port",
  Logged: "Logged",
  theme: "Themes",
  append: "append",
  home: "Home",
  issues: "Issues",
  overlay: "Overlay",
  order: "Order",
  proxy: "Proxy",
  general: "General",
  advanced: "Advanced",
  change: "Change",
  export: "Export",
  "local-import": "Local Import",
  about: "About",
  never: "Never",
  remote: "Remote",
  local: "Local",
  quit: "Quit",
  settings: {
    default: "Setting",
    advanced: {
      title: `Help fix ${APP_NAME}`,
      tip: `Help improve ${APP_NAME} by sending anonymous usage data? The data does not contain any private information.`,
    },
  },
  login: {
    btn: "Login",
    account: "Account",
  },
  主机: "Host",
  更多: "More",
  回收站: "Recycle",
  来源: "Source",
  微博: "Weibo",
  检查更新: "Check for updates",
  偏好设置: "Preferences",
  你访问的页面不存在: "The page you are visiting does not exist",
  返回首页: "Return home",
  从远程导入: "Import from remote",
  "我的 Hosts 文件在哪里？": "Where is my Hosts file?",
  "添加新的 Hosts 内容": "Add new Hosts content",
  请输入账号: "Please input Username",
  写入模式: "Write mode",
  选择主题色: "Choose theme color",
  选择模式: "Select mode",
  "只对顶层项目生效，每个文件夹可设置自己的选择模式。":
    "It only takes effect for the top-level project, and each folder can set its own selection mode.",
  选择语言: "Choose a language",
  显示托盘标题: "Show Tray Title",
  启动时隐藏: "Hide at startup",
  "新记录将覆盖现有系统 Hosts 的文件内容":
    "The new record will overwrite the contents of the existing system Hosts file",
  "新记录将追加到现有系统 Hosts 的文件末尾":
    "The new record will be appended to the end of the existing system Hosts file",
  "更新配置成功！": "The update configuration is successful!",
  "好的，发送匿名的使用数据": "OK, send anonymous usage data",
  "我的 Hosts 文件在哪？": "Where is my Hosts file?",
  "你的 Hosts 文件在：": "Your Hosts file is in:",
  "我的数据储存在哪里？": "Where is my data stored?",
  "你的数据文件在：": "Your data files are in:",
  点击打开: " Click to open",
  输入主机地址: "Enter host address",
  请输入端口: "Please enter the port",
  使用代理: "Use proxy",
  协议: "Protocol",
  名称: "Name",
  选择协议: "Choose agreement",
  创建失败: "Creation failed",
  创建成功: "Created successfully",
  "创建 Hosts": "Create Hosts",
  "编辑 Hosts": "Modify Hosts",
  请选择刷新类型: "Please select a refresh type",
  "请输入远程 Url 地址": "Please enter the remote URL address",
  "请输入正确的远程 Url 地址": "Please enter the correct remote URL address",
  "请选择 Hosts 类型": "Please select the Hosts type",
  远程地址: "Remote URL",
  刷新类型: "Refresh type",
  "Hosts 类型": "Hosts type",
  请输入远程地址: "Please enter the remote address",
  请输入名称: "Please enter a name",
  分钟: "{m}  minute",
  小时: "{s}  hour",
  天: "{d} day",
};
